[project]
name = 'Islamic-Finance-Compliant-Lending'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Islamic-Finance-Compliant-Lending]
path = 'contracts/Islamic-Finance-Compliant-Lending.clar'
clarity_version = 3
epoch = 3.1

[contracts.profit-distribution]
path = 'contracts/profit-distribution.clar'
clarity_version = 3
epoch = 3.1
[contracts.wakala-fees]
path = 'contracts/wakala-fees.clar'
clarity_version = 3
epoch = 3.1
[contracts.loan-extension]
path = 'contracts/loan-extension.clar'
clarity_version = 3
epoch = 3.1

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
